<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMovieComments($id)
    {
        return $this->createQueryBuilder('c')
            ->leftJoin("c.user", "u")
            ->addSelect("u")
            ->leftJoin("c.children", "ch")
            ->addSelect("ch")
            ->where('c.movie_id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }
}
