<?php

namespace AppBundle\Repository;

/**
 * MovieUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMovieUserInDatabase($user_id, $movie_id)
    {
        return $this->createQueryBuilder('m')
            ->where('m.movie = :movie_id')
            ->setParameter('movie_id', $movie_id)
            ->andWhere('m.user = :user_id')
            ->setParameter('user_id', $user_id)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
